#spring:
#  application:
#    name: eureka-client
#eureka:
#  client:
#    eureka-server-port: 8761
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#    enabled: true
#  instance:
#    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 30
#
spring.application.name=eureka-client
server.port=0
#Порт сервера Eureka
eureka.client.eureka-server-port=8761
#Карта зоны доступности для списка полностью определенных URL-адресов для связи с сервером eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#Флаг, указывающий, что клиент Eureka включен
eureka.client.enabled=true
#Использование IP-адреса
eureka.instance.prefer-ip-address=true
#Указывает, как часто (в секундах) клиенту eureka необходимо отправлять сигналы heartbeat
# на сервер eureka, чтобы указать, что он все еще жив
eureka.instance.lease-renewal-interval-in-seconds=35
#Интервал эхо-запросов клиента на сервер о его(сервера) изменениях
eureka.client.eureka-service-url-poll-interval-seconds=35


