server:
  port: 8081
spring:
  application:
    name: creation-book-service
  cloud:
    config:
      enabled: false
    stream:
      kafka:
        binder:
          auto-add-partitions: true
  profiles:
    active: native


