spring.application.name=eureka-server
server.port=8761
eureka.client.register-with-eureka=false

#Информация из реестра
eureka.client.fetch-registry=false
#Время ожидания сервера
eureka.client.eureka-server-connect-timeout-seconds=60
#Интервал получения изменений с сервера
eureka.client.eureka-service-url-poll-interval-seconds=15
#Запрет на днс
eureka.client.use-dns-for-fetching-service-urls=false
#Если возникнут проблемы в сети, то запретить клиент
eureka.server.renewal-percent-threshold=0.85
#Использовать сервер Eureka в той же зоне
eureka.client.prefer-same-zone-eureka=true
#Проверка работоспособности клиента Eureka
eureka.client.healthcheck.enabled=true
#Время ожидания сервера эхо-запроса от клиента о том, что он жив
eureka.instance.lease-renewal-interval-in-seconds=20
#Если Eureka Server не видел изменений в течение 70с, то удаляет экземпляр
eureka.instance.lease-expiration-duration-in-seconds=70

