server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}

spring:
  application:
    name: client-service

  #  config:
  #    import: 'optional:configserver:'
  cloud:
    config:
      enabled: false
  profiles:
    active: native