server.port=8888

spring.application.name=config-server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

#Тип хранения профиля (локально - native, или удаленно на гите - git)
spring.profiles.active=native
#Параметры для удаленного хранение профиля
#spring.cloud.config.server.git.uri=тут должна быть ссылка на гитхаб

#Параметры для локального хранения профиля
#ms-config-properties - название папки, которая будет хранить файлы свойств для каждого отдельного клиента
#{application} - название приложения. Должно совпадать с параметром name в файле свойств у клиента, который будет запрашивать конкретно этот файл свойств
#{profile}- профиль приложения. dev, master или test.
spring.cloud.config.server.native.search-locations=file://${user.home}/IdeaProjects/spring-cloud-course/ms-config-properties/{application}